diff --git a/9.4/Dockerfile b/9.4/Dockerfile
index 171997f..23709ad 100644
--- a/9.4/Dockerfile
+++ b/9.4/Dockerfile
@@ -46,8 +46,8 @@ RUN set -ex; \
 	rm -rf "$GNUPGHOME"; \
 	apt-key list
 
-ENV PG_MAJOR 9.4
-ENV PG_VERSION 9.4.15-1.pgdg80+1
+ARG PG_MAJOR=9.4
+ARG PG_VERSION
 
 RUN set -ex; \
 	\
