diff --git a/9.4/Dockerfile b/9.4/Dockerfile
index 21e7852..b4a4020 100644
--- a/9.4/Dockerfile
+++ b/9.4/Dockerfile
@@ -8 +8 @@ RUN groupadd -r postgres --gid=999 && useradd -r -g postgres --uid=999 postgres
-ENV GOSU_VERSION 1.7
+ENV GOSU_VERSION 1.9
@@ -30,4 +30,2 @@ RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A4
-ENV PG_MAJOR 9.4
-ENV PG_VERSION 9.4.8-1.pgdg80+1
-
-RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list
+ARG PG_MAJOR=9.4
+ARG PG_VERSION
