--- 9.4/Dockerfile	2016-01-09 18:26:26.709013900 +0000
+++ 9.4/Dockerfile	2016-01-10 11:02:09.229061700 +0000
@@ -23,10 +23,8 @@
 
 RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
 
-ENV PG_MAJOR 9.4
-ENV PG_VERSION 9.4.5-1.pgdg80+1
-
-RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list
+ARG PG_MAJOR=9.4
+ARG PG_VERSION
 
 RUN apt-get update \
 	&& apt-get install -y postgresql-common \
