diff --git postgres/11/Dockerfile postgres/11/Dockerfile
index ddc6889..f4f0bdf
--- postgres/11/Dockerfile
+++ postgres/11/Dockerfile
@@ -86 +86 @@ ENV PG_MAJOR 11
-ENV PG_VERSION 11.8-1.pgdg90+1
+ENV PG_VERSION 11.7-0+deb10u1
@@ -94,0 +95,2 @@ RUN set -ex; \
+		*) apt-get update; \
+			;; \
