diff --git a/9.4/Dockerfile b/9.4/Dockerfile
index 171997f..735baf8 100644
--- a/9.4/Dockerfile
+++ b/9.4/Dockerfile
@@ -50 +50 @@ RUN set -ex; \
-ENV PG_VERSION 9.4.17-1.pgdg80+1
+ENV PG_VERSION 9.4.15-0+deb8u1
@@ -56 +56 @@ RUN set -ex; \
-		amd64|i386|ppc64el) \
+		*) apt-get update;; *) \
